url: "https://adrianherrera.github.io"
baseurl: ""

title: Adrian Herrera
description: Personal website
author: Adrian Herrera

remote_theme: daattali/beautiful-jekyll@master
avatar: "/assets/img/head.jpg"
paginate_path: "/blog/page:num/"

navbar-links:
  Blog: blog
  Talks: talks
  Publications: publications
  Service: service

social-network-links:
  github: adrianherrera
  bluesky: adrianherrera.bsky.social
  twitter: 0xadr1an
  linkedin: adrian-herrera-53425a260
  google-scholar: ghtw2qwAAAAJ
  ORCID: 0000-0001-9234-1694
